name: CI of mc_vrep

on:
  push:
    paths-ignore:
      # Changes to those files don't mandate running CI
      - ".github/workflows/sync.yml"
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  clang-format:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Install clang-format-10
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install clang-format-10
    - name: Run clang-format-check
      run: |
        ./.clang-format-check.sh
  build:
    needs: clang-format
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        compiler: [gcc]
        build-type: [RelWithDebInfo]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup extra APT mirror
      if: startsWith(runner.os, 'Linux')
      run: |
        set -x
        set -e
        curl -1sLf 'https://dl.cloudsmith.io/public/mc-rtc/head/setup.deb.sh' | sudo -E bash
    - name: Install mc_rtc
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        compiler: ${{matrix.compiler}}
        build-type: ${{ matrix.build-type }}
        ubuntu: |
          apt: libmc-rtc-dev
    - name: Install CoppeliaSim
      run: |
        cd /tmp
        if [ "${{ matrix.os }}" = "ubuntu-18.04" ]
        then
          wget https://www.coppeliarobotics.com/files/CoppeliaSim_Edu_V4_2_0_Ubuntu18_04.tar.xz
          tar xJf CoppeliaSim_Edu_V4_2_0_Ubuntu18_04.tar.xz
          echo "VREP_PATH=/tmp/CoppeliaSim_Edu_V4_2_0_Ubuntu18_04" >> $GITHUB_ENV
        else
          wget https://www.coppeliarobotics.com/files/CoppeliaSim_Edu_V4_2_0_Ubuntu20_04.tar.xz
          tar xJf CoppeliaSim_Edu_V4_2_0_Ubuntu20_04.tar.xz
          echo "VREP_PATH=/tmp/CoppeliaSim_Edu_V4_2_0_Ubuntu20_04" >> $GITHUB_ENV
        fi
    - name: Install vrep-api-wrapper
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
        github: |
          - path: https://gite.lirmm.fr/vrep-utils/vrep-api-wrapper
            options: -DVREP_PATH=${{ env.VREP_PATH }}
    - name: Build and test
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
